name: openclash-R66s-24

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 18 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-mark hold grub-efi-amd64-signed
          sudo -E apt update
          sudo -E apt -y full-upgrade
          sudo -E apt-get -y purge azure-cli* docker* ghc* llvm* firefox* google* dotnet* aspnetcore* powershell* mysql* php* mongodb* snap*
          sudo -E apt -y install build-essential git libncurses-dev libpython3-dev python3-setuptools python3-pyelftools swig
          sudo -E systemctl daemon-reload
          sudo -E apt -y autoremove --purge
          sudo -E apt autoclean
          sudo -E apt clean
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL /usr/local/.ghcup /usr/share/swift /usr/local/share/powershell /usr/local/lib/heroku
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: Check disk space
        run: df -h

      - name: Download and Extract Source Code
        run: |
          rm -rf .git/ .github/ *
          OPENWRT_LATEST=$(curl -s "https://api.github.com/repos/immortalwrt/immortalwrt/tags" | grep '"name": "v24' | head -n 1 | cut -d '"' -f 4)
          CLASH_LATEST=$(curl -s "https://api.github.com/repos/vernesong/OpenClash/tags" | grep 'name' | head -n 1 | cut -d '"' -f 4)
          echo "Downloading $OPENWRT_LATEST... and $CLASH_LATEST "
          wget "https://github.com/immortalwrt/immortalwrt/archive/refs/tags/$OPENWRT_LATEST.zip" -O openwrt_latest.zip
          wget "https://github.com/vernesong/OpenClash/archive/refs/tags/$CLASH_LATEST.zip" -O openclash_latest.zip
          OP_TAG=$(echo "$OPENWRT_LATEST" | sed 's/^v//')
          CA_TAG=$(echo "$CLASH_LATEST" | sed 's/^v//')
          echo "Extracting version: $OP_TAG and $CA_TAG"
          unzip -q openwrt_latest.zip -d .
          unzip -q openclash_latest.zip -d .
          mv "immortalwrt-$OP_TAG"/* .
          mv "OpenClash-$CA_TAG"/luci-app-openclash package/
          rm -rf "immortalwrt-$OP_TAG" "OpenClash-$CA_TAG" openwrt_latest.zip openclash_latest.zip

          git clone --depth=1 --branch=master https://github.com/AutoCONFIG/syncthing.git tmp/syncthing
          git clone --depth=1 --branch=master https://github.com/AutoCONFIG/rustdesk-server.git tmp/rustdesk-server
          git clone --depth=1 --branch=master https://github.com/AutoCONFIG/luci-app-rustdesk-server.git tmp/luci-app-rustdesk-server
          git clone --depth=1 --branch=master https://github.com/AutoCONFIG/vlmcsd.git tmp/vlmcsd
          git clone --depth=1 --branch=master https://github.com/AutoCONFIG/luci-app-vlmcsd.git tmp/luci-app-vlmcsd

      - name: Others
        run: |
          sed -i \
            -e 's/CONFIG_TARGET_x86/CONFIG_TARGET_rockchip/' \
            -e 's/+TARGET_x86:ethtool[[:space:]]*\\[[:space:]]*$/+TARGET_rockchip:ethtool/' \
            -e 's/+TARGET_x86:ethtool$/+TARGET_rockchip:ethtool/' \
            -e '/+TARGET_x86:lm-sensors/d' \
            -e 's/ifneq ($(filter i386 i686 x86_64, $(ARCH)),)/ifneq ($(filter i386 i686 aarch64, $(ARCH)),)/' package/emortal/autocore/Makefile

          sed -i 's/+kmod-nft-fullcone //' package/network/config/firewall4/Makefile

          rm -rf package/network/utils/fullconenat-nft
          rm -rf package/network/config/firewall4/patches/001-firewall4-add-support-for-fullcone-nat.patch
          rm -rf package/network/utils/nftables/patches/002-nftables-add-fullcone-expression-support.patch
          rm -rf package/libs/libnftnl/patches/001-libnftnl-add-fullcone-expression-support.patch

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          rm -rf feeds/luci/applications/luci-app-openclash feeds/luci/applications/luci-app-rustdesk-server feeds/luci/applications/luci-app-vlmcsd
          rm -rf feeds/packages/net/rustdesk-server feeds/packages/net/vlmcsd feeds/packages/utils/syncthing
          mv tmp/luci-app-* feeds/luci/applications
          mv tmp/rustdesk-server feeds/packages/net
          mv tmp/vlmcsd feeds/packages/net
          mv tmp/syncthing feeds/packages/utils
          rm -rf tmp/
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config

          cat >> .config <<EOF
          CONFIG_TARGET_rockchip=y
          CONFIG_TARGET_rockchip_armv8=y
          CONFIG_TARGET_rockchip_armv8_DEVICE_lunzn_fastrhino-r66s=y
          CONFIG_PACKAGE_kmod-tcp-bbr=y
          CONFIG_PACKAGE_luci-app-ddns-go=y
          # CONFIG_PACKAGE_luci-app-diskman_INCLUDE_btrfs_progs is not set
          # CONFIG_PACKAGE_luci-app-diskman_INCLUDE_lsblk is not set
          CONFIG_PACKAGE_luci-app-dockerman=y
          CONFIG_PACKAGE_luci-app-frpc=y
          CONFIG_PACKAGE_luci-app-frps=y
          CONFIG_PACKAGE_luci-app-ksmbd=y
          CONFIG_PACKAGE_luci-app-openclash=y
          CONFIG_PACKAGE_luci-app-openvpn=y
          # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-ng is not set
          # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-webui is not set
          CONFIG_PACKAGE_luci-app-rustdesk-server=y
          CONFIG_PACKAGE_luci-app-syncthing=y
          CONFIG_PACKAGE_luci-app-upnp=y
          CONFIG_PACKAGE_luci-app-vlmcsd=y
          CONFIG_PACKAGE_openvpn-openssl=y
          CONFIG_PACKAGE_rsync=y
          CONFIG_TARGET_ROOTFS_PARTSIZE=1024
          EOF

          #
          # ===============================================================
          # 

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Download packages
        run: make download -j16
    
      - name: Build firmware
        run: |
          make -j$(nproc) || make -j1 V=s
    
      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/packages/ -type f \( -name "*.ipk" -o -name "*.apk" \)) ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/
    
      - name: Upload buildinfo
        uses: actions/upload-artifact@master
        with:
          name: immortalwrt_buildinfo
          path: ./artifact/buildinfo/
    
      - name: Upload package
        uses: actions/upload-artifact@master
        with:
          name: immortalwrt_package
          path: ./artifact/package/
    
      - name: Upload firmware
        uses: actions/upload-artifact@master
        with:
          name: immortalwrt_firmware
          path: ./bin/targets/
